/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.loadstatus;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class KeySchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5165706004041985143L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"KeySchema\",\"namespace\":\"net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.loadstatus\",\"fields\":[{\"name\":\"messageKey\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.KeySchema\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<KeySchema> ENCODER =
      new BinaryMessageEncoder<KeySchema>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<KeySchema> DECODER =
      new BinaryMessageDecoder<KeySchema>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<KeySchema> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<KeySchema> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<KeySchema> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<KeySchema>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this KeySchema to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a KeySchema from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a KeySchema instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static KeySchema fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence messageKey;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public KeySchema() {}

  /**
   * All-args constructor.
   * @param messageKey The new value for messageKey
   */
  public KeySchema(java.lang.CharSequence messageKey) {
    this.messageKey = messageKey;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return messageKey;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: messageKey = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'messageKey' field.
   * @return The value of the 'messageKey' field.
   */
  public java.lang.CharSequence getMessageKey() {
    return messageKey;
  }


  /**
   * Sets the value of the 'messageKey' field.
   * @param value the value to set.
   */
  public void setMessageKey(java.lang.CharSequence value) {
    this.messageKey = value;
  }

  /**
   * Creates a new KeySchema RecordBuilder.
   * @return A new KeySchema RecordBuilder
   */
  public static net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.loadstatus.KeySchema.Builder newBuilder() {
    return new net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.loadstatus.KeySchema.Builder();
  }

  /**
   * Creates a new KeySchema RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new KeySchema RecordBuilder
   */
  public static net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.loadstatus.KeySchema.Builder newBuilder(net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.loadstatus.KeySchema.Builder other) {
    if (other == null) {
      return new net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.loadstatus.KeySchema.Builder();
    } else {
      return new net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.loadstatus.KeySchema.Builder(other);
    }
  }

  /**
   * Creates a new KeySchema RecordBuilder by copying an existing KeySchema instance.
   * @param other The existing instance to copy.
   * @return A new KeySchema RecordBuilder
   */
  public static net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.loadstatus.KeySchema.Builder newBuilder(net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.loadstatus.KeySchema other) {
    if (other == null) {
      return new net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.loadstatus.KeySchema.Builder();
    } else {
      return new net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.loadstatus.KeySchema.Builder(other);
    }
  }

  /**
   * RecordBuilder for KeySchema instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<KeySchema>
    implements org.apache.avro.data.RecordBuilder<KeySchema> {

    private java.lang.CharSequence messageKey;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.loadstatus.KeySchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.messageKey)) {
        this.messageKey = data().deepCopy(fields()[0].schema(), other.messageKey);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing KeySchema instance
     * @param other The existing instance to copy.
     */
    private Builder(net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.loadstatus.KeySchema other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.messageKey)) {
        this.messageKey = data().deepCopy(fields()[0].schema(), other.messageKey);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'messageKey' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessageKey() {
      return messageKey;
    }


    /**
      * Sets the value of the 'messageKey' field.
      * @param value The value of 'messageKey'.
      * @return This builder.
      */
    public net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.loadstatus.KeySchema.Builder setMessageKey(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.messageKey = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'messageKey' field has been set.
      * @return True if the 'messageKey' field has been set, false otherwise.
      */
    public boolean hasMessageKey() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'messageKey' field.
      * @return This builder.
      */
    public net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.loadstatus.KeySchema.Builder clearMessageKey() {
      messageKey = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public KeySchema build() {
      try {
        KeySchema record = new KeySchema();
        record.messageKey = fieldSetFlags()[0] ? this.messageKey : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<KeySchema>
    WRITER$ = (org.apache.avro.io.DatumWriter<KeySchema>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<KeySchema>
    READER$ = (org.apache.avro.io.DatumReader<KeySchema>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.messageKey);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.messageKey = in.readString(this.messageKey instanceof Utf8 ? (Utf8)this.messageKey : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.messageKey = in.readString(this.messageKey instanceof Utf8 ? (Utf8)this.messageKey : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










