/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class arrivalVoyage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8504463575679005903L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"arrivalVoyage\",\"namespace\":\"net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis\",\"fields\":[{\"name\":\"voyage\",\"type\":\"string\"},{\"name\":\"direction\",\"type\":\"string\"},{\"name\":\"transportMode\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.arrivalVoyage\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<arrivalVoyage> ENCODER =
      new BinaryMessageEncoder<arrivalVoyage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<arrivalVoyage> DECODER =
      new BinaryMessageDecoder<arrivalVoyage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<arrivalVoyage> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<arrivalVoyage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<arrivalVoyage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<arrivalVoyage>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this arrivalVoyage to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a arrivalVoyage from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a arrivalVoyage instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static arrivalVoyage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence voyage;
  @Deprecated public java.lang.CharSequence direction;
  @Deprecated public java.lang.CharSequence transportMode;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public arrivalVoyage() {}

  /**
   * All-args constructor.
   * @param voyage The new value for voyage
   * @param direction The new value for direction
   * @param transportMode The new value for transportMode
   */
  public arrivalVoyage(java.lang.CharSequence voyage, java.lang.CharSequence direction, java.lang.CharSequence transportMode) {
    this.voyage = voyage;
    this.direction = direction;
    this.transportMode = transportMode;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return voyage;
    case 1: return direction;
    case 2: return transportMode;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: voyage = (java.lang.CharSequence)value$; break;
    case 1: direction = (java.lang.CharSequence)value$; break;
    case 2: transportMode = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'voyage' field.
   * @return The value of the 'voyage' field.
   */
  public java.lang.CharSequence getVoyage() {
    return voyage;
  }


  /**
   * Sets the value of the 'voyage' field.
   * @param value the value to set.
   */
  public void setVoyage(java.lang.CharSequence value) {
    this.voyage = value;
  }

  /**
   * Gets the value of the 'direction' field.
   * @return The value of the 'direction' field.
   */
  public java.lang.CharSequence getDirection() {
    return direction;
  }


  /**
   * Sets the value of the 'direction' field.
   * @param value the value to set.
   */
  public void setDirection(java.lang.CharSequence value) {
    this.direction = value;
  }

  /**
   * Gets the value of the 'transportMode' field.
   * @return The value of the 'transportMode' field.
   */
  public java.lang.CharSequence getTransportMode() {
    return transportMode;
  }


  /**
   * Sets the value of the 'transportMode' field.
   * @param value the value to set.
   */
  public void setTransportMode(java.lang.CharSequence value) {
    this.transportMode = value;
  }

  /**
   * Creates a new arrivalVoyage RecordBuilder.
   * @return A new arrivalVoyage RecordBuilder
   */
  public static net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage.Builder newBuilder() {
    return new net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage.Builder();
  }

  /**
   * Creates a new arrivalVoyage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new arrivalVoyage RecordBuilder
   */
  public static net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage.Builder newBuilder(net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage.Builder other) {
    if (other == null) {
      return new net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage.Builder();
    } else {
      return new net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage.Builder(other);
    }
  }

  /**
   * Creates a new arrivalVoyage RecordBuilder by copying an existing arrivalVoyage instance.
   * @param other The existing instance to copy.
   * @return A new arrivalVoyage RecordBuilder
   */
  public static net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage.Builder newBuilder(net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage other) {
    if (other == null) {
      return new net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage.Builder();
    } else {
      return new net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage.Builder(other);
    }
  }

  /**
   * RecordBuilder for arrivalVoyage instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<arrivalVoyage>
    implements org.apache.avro.data.RecordBuilder<arrivalVoyage> {

    private java.lang.CharSequence voyage;
    private java.lang.CharSequence direction;
    private java.lang.CharSequence transportMode;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.voyage)) {
        this.voyage = data().deepCopy(fields()[0].schema(), other.voyage);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.direction)) {
        this.direction = data().deepCopy(fields()[1].schema(), other.direction);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.transportMode)) {
        this.transportMode = data().deepCopy(fields()[2].schema(), other.transportMode);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing arrivalVoyage instance
     * @param other The existing instance to copy.
     */
    private Builder(net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.voyage)) {
        this.voyage = data().deepCopy(fields()[0].schema(), other.voyage);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.direction)) {
        this.direction = data().deepCopy(fields()[1].schema(), other.direction);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.transportMode)) {
        this.transportMode = data().deepCopy(fields()[2].schema(), other.transportMode);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'voyage' field.
      * @return The value.
      */
    public java.lang.CharSequence getVoyage() {
      return voyage;
    }


    /**
      * Sets the value of the 'voyage' field.
      * @param value The value of 'voyage'.
      * @return This builder.
      */
    public net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage.Builder setVoyage(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.voyage = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'voyage' field has been set.
      * @return True if the 'voyage' field has been set, false otherwise.
      */
    public boolean hasVoyage() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'voyage' field.
      * @return This builder.
      */
    public net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage.Builder clearVoyage() {
      voyage = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'direction' field.
      * @return The value.
      */
    public java.lang.CharSequence getDirection() {
      return direction;
    }


    /**
      * Sets the value of the 'direction' field.
      * @param value The value of 'direction'.
      * @return This builder.
      */
    public net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage.Builder setDirection(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.direction = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'direction' field has been set.
      * @return True if the 'direction' field has been set, false otherwise.
      */
    public boolean hasDirection() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'direction' field.
      * @return This builder.
      */
    public net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage.Builder clearDirection() {
      direction = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'transportMode' field.
      * @return The value.
      */
    public java.lang.CharSequence getTransportMode() {
      return transportMode;
    }


    /**
      * Sets the value of the 'transportMode' field.
      * @param value The value of 'transportMode'.
      * @return This builder.
      */
    public net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage.Builder setTransportMode(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.transportMode = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'transportMode' field has been set.
      * @return True if the 'transportMode' field has been set, false otherwise.
      */
    public boolean hasTransportMode() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'transportMode' field.
      * @return This builder.
      */
    public net.apmoller.crb.gcd.microservices.eventstream.integration.events.payload.gsis.arrivalVoyage.Builder clearTransportMode() {
      transportMode = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public arrivalVoyage build() {
      try {
        arrivalVoyage record = new arrivalVoyage();
        record.voyage = fieldSetFlags()[0] ? this.voyage : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.direction = fieldSetFlags()[1] ? this.direction : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.transportMode = fieldSetFlags()[2] ? this.transportMode : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<arrivalVoyage>
    WRITER$ = (org.apache.avro.io.DatumWriter<arrivalVoyage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<arrivalVoyage>
    READER$ = (org.apache.avro.io.DatumReader<arrivalVoyage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.voyage);

    out.writeString(this.direction);

    out.writeString(this.transportMode);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.voyage = in.readString(this.voyage instanceof Utf8 ? (Utf8)this.voyage : null);

      this.direction = in.readString(this.direction instanceof Utf8 ? (Utf8)this.direction : null);

      this.transportMode = in.readString(this.transportMode instanceof Utf8 ? (Utf8)this.transportMode : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.voyage = in.readString(this.voyage instanceof Utf8 ? (Utf8)this.voyage : null);
          break;

        case 1:
          this.direction = in.readString(this.direction instanceof Utf8 ? (Utf8)this.direction : null);
          break;

        case 2:
          this.transportMode = in.readString(this.transportMode instanceof Utf8 ? (Utf8)this.transportMode : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










