//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.27 at 03:27:55 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.ibm.maersk.hermes", location = "http://com.ibm.maersk.hermes Command.xsd",

xmlns = {
		@javax.xml.bind.annotation.XmlNs(prefix = "cmd", namespaceURI = "http://com.ibm.maersk.hermes"),
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://com.ibm.maersk.hermes/CommonTypes", prefix = "type"),
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.w3.org/2001/XMLSchema-instance", prefix = "xsi") },
//location="http://com.ibm.maersk.hermes Command.xsd",
/*@javax.xml.bind.annotation.XmlSchema(location="http://com.ibm.maersk.hermes Command.xsd",prefix="schemaLocation")},*/elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.apmoller.crb.gcd.microservices.eventstream.integration.model;

