//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.20 at 02:47:47 PM IST 
//

package net.apmoller.crb.gcd.microservices.eventstream.integration.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.DateSerializer;

import net.apmoller.crb.gcd.microservices.eventstream.integration.util.CustomDateDeserializer;
import net.apmoller.crb.gcd.microservices.eventstream.integration.util.CustomDateSerializer;

/**
 * <p>
 * Java class for ResponseMessage complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sourceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="evwRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="iChgCtrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vesselCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="loadPort" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="exportVoyage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dischargePort" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dischargeVoyage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sentTS" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="recdTS" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="lodgementStatusResponse" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="responseSenderReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="responseReceiverReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="senderInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="lodgementStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="lodgementStatusDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="dates" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="dateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="dateTimeKind" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="custResponse" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="tpDocNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="customRefNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="dispCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="sendingCntry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="itemNbr" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="responseDetail" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="codeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="itemNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="subItemNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="subItemNbr2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="errorReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="errorReasonDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="origAttribValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="remarks" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="remarks_LNG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="remarks" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="remarks_LNG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "sourceID", "evwRef", "iChgCtrl",
		"vesselCode", "loadPort", "exportVoyage", "dischargePort",
		"dischargeVoyage", "sentTS", "recdTS", "lodgementStatusResponse",
		"custResponse" })
@XmlRootElement(name = "ResponseMessage")
public class ResponseMessage {

	/** The source ID. */
	@XmlElement(required = true)
	protected String sourceID;

	/** The evw ref. */
	@XmlElement(required = true)
	protected String evwRef;

	/** The i chg ctrl. */
	@XmlElement(required = true)
	protected String iChgCtrl;

	/** The vessel code. */
	protected String vesselCode;

	/** The load port. */
	protected String loadPort;

	/** The export voyage. */
	protected String exportVoyage;

	/** The discharge port. */
	protected String dischargePort;

	/** The discharge voyage. */
	protected String dischargeVoyage;

	/** The sent TS. */
	@XmlElement(name = "sentTS", required = true)
	//@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
	protected Date sentTS;

	/** The recd TS. */
	@XmlElement(name = "recdTS", required = true)
	//@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
	protected Date recdTS;

	/** The lodgement status response. */
	protected ResponseMessage.LodgementStatusResponse lodgementStatusResponse;

	/** The cust response. */
	protected List<ResponseMessage.CustResponse> custResponse;

	/**
	 * Gets the value of the sourceID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSourceID() {
		return sourceID;
	}

	/**
	 * Sets the value of the sourceID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSourceID(String value) {
		this.sourceID = value;
	}

	/**
	 * Gets the value of the evwRef property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEvwRef() {
		return evwRef;
	}

	/**
	 * Sets the value of the evwRef property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEvwRef(String value) {
		this.evwRef = value;
	}

	/**
	 * Gets the value of the iChgCtrl property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIChgCtrl() {
		return iChgCtrl;
	}

	/**
	 * Sets the value of the iChgCtrl property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIChgCtrl(String value) {
		this.iChgCtrl = value;
	}

	/**
	 * Gets the value of the vesselCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVesselCode() {
		return vesselCode;
	}

	/**
	 * Sets the value of the vesselCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVesselCode(String value) {
		this.vesselCode = value;
	}

	/**
	 * Gets the value of the loadPort property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLoadPort() {
		return loadPort;
	}

	/**
	 * Sets the value of the loadPort property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLoadPort(String value) {
		this.loadPort = value;
	}

	/**
	 * Gets the value of the exportVoyage property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getExportVoyage() {
		return exportVoyage;
	}

	/**
	 * Sets the value of the exportVoyage property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setExportVoyage(String value) {
		this.exportVoyage = value;
	}

	/**
	 * Gets the value of the dischargePort property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDischargePort() {
		return dischargePort;
	}

	/**
	 * Sets the value of the dischargePort property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDischargePort(String value) {
		this.dischargePort = value;
	}

	/**
	 * Gets the value of the dischargeVoyage property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDischargeVoyage() {
		return dischargeVoyage;
	}

	/**
	 * Sets the value of the dischargeVoyage property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDischargeVoyage(String value) {
		this.dischargeVoyage = value;
	}

	/**
	 * Gets the value of the sentTS property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public Date getSentTS() {
		return sentTS;
	}

	public void setSentTS(Date sentTS) {
		this.sentTS = sentTS;
	}

	public Date getRecdTS() {
		return recdTS;
	}

	public void setRecdTS(Date recdTS) {
		this.recdTS = recdTS;
	}
	
	/**
	 * Gets the value of the lodgementStatusResponse property.
	 * 
	 * @return possible object is
	 *         {@link ResponseMessage.LodgementStatusResponse }
	 * 
	 */
	public ResponseMessage.LodgementStatusResponse getLodgementStatusResponse() {
		return lodgementStatusResponse;
	}


	/**
	 * Sets the value of the lodgementStatusResponse property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link ResponseMessage.LodgementStatusResponse }
	 * 
	 */
	public void setLodgementStatusResponse(
			ResponseMessage.LodgementStatusResponse value) {
		this.lodgementStatusResponse = value;
	}

	/**
	 * Gets the value of the custResponse property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the custResponse property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCustResponse().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ResponseMessage.CustResponse }
	 * 
	 * @return the cust response
	 */
	public List<ResponseMessage.CustResponse> getCustResponse() {
		if (custResponse == null) {
			custResponse = new ArrayList<ResponseMessage.CustResponse>();
		}
		return this.custResponse;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="tpDocNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="customRefNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="dispCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="sendingCntry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="itemNbr" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
	 *         &lt;element name="responseDetail" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="codeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="itemNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="subItemNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="subItemNbr2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="errorReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="errorReasonDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="origAttribValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="remarks" maxOccurs="unbounded" minOccurs="0">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                             &lt;element name="remarks_LNG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="remarks" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="remarks_LNG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "tpDocNbr", "customRefNbr", "dispCode",
			"sendingCntry", "itemNbr", "responseDetail", "remarks" })
	public static class CustResponse {

		/** The tp doc nbr. */
		protected String tpDocNbr;

		/** The custom ref nbr. */
		protected String customRefNbr;

		/** The disp code. */
		@XmlElement(required = true)
		protected String dispCode;

		/** The sending cntry. */
		@XmlElement(required = true)
		protected String sendingCntry;

		/** The item nbr. */
		protected BigInteger itemNbr;

		/** The response detail. */
		protected List<ResponseMessage.CustResponse.ResponseDetail> responseDetail;

		/** The remarks. */
		protected ResponseMessage.CustResponse.Remarks remarks;

		/**
		 * Gets the value of the tpDocNbr property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getTpDocNbr() {
			return tpDocNbr;
		}

		/**
		 * Sets the value of the tpDocNbr property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setTpDocNbr(String value) {
			this.tpDocNbr = value;
		}

		/**
		 * Gets the value of the customRefNbr property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCustomRefNbr() {
			return customRefNbr;
		}

		/**
		 * Sets the value of the customRefNbr property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCustomRefNbr(String value) {
			this.customRefNbr = value;
		}

		/**
		 * Gets the value of the dispCode property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDispCode() {
			return dispCode;
		}

		/**
		 * Sets the value of the dispCode property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDispCode(String value) {
			this.dispCode = value;
		}

		/**
		 * Gets the value of the sendingCntry property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSendingCntry() {
			return sendingCntry;
		}

		/**
		 * Sets the value of the sendingCntry property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSendingCntry(String value) {
			this.sendingCntry = value;
		}

		/**
		 * Gets the value of the itemNbr property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getItemNbr() {
			return itemNbr;
		}

		/**
		 * Sets the value of the itemNbr property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setItemNbr(BigInteger value) {
			this.itemNbr = value;
		}

		/**
		 * Gets the value of the responseDetail property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the responseDetail property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getResponseDetail().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link ResponseMessage.CustResponse.ResponseDetail }
		 * 
		 * @return the response detail
		 */
		public List<ResponseMessage.CustResponse.ResponseDetail> getResponseDetail() {
			if (responseDetail == null) {
				responseDetail = new ArrayList<ResponseMessage.CustResponse.ResponseDetail>();
			}
			return this.responseDetail;
		}

		/**
		 * Gets the value of the remarks property.
		 * 
		 * @return possible object is
		 *         {@link ResponseMessage.CustResponse.Remarks }
		 * 
		 */
		public ResponseMessage.CustResponse.Remarks getRemarks() {
			return remarks;
		}

		/**
		 * Sets the value of the remarks property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link ResponseMessage.CustResponse.Remarks }
		 * 
		 */
		public void setRemarks(ResponseMessage.CustResponse.Remarks value) {
			this.remarks = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="remarks_LNG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "remarks", "remarksLNG" })
		public static class Remarks {

			/** The remarks. */
			protected String remarks;

			/** The remarks LNG. */
			@XmlElement(name = "remarks_LNG")
			protected String remarksLNG;

			/**
			 * Gets the value of the remarks property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getRemarks() {
				return remarks;
			}

			/**
			 * Sets the value of the remarks property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setRemarks(String value) {
				this.remarks = value;
			}

			/**
			 * Gets the value of the remarksLNG property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getRemarksLNG() {
				return remarksLNG;
			}

			/**
			 * Sets the value of the remarksLNG property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setRemarksLNG(String value) {
				this.remarksLNG = value;
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="codeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="itemNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="subItemNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="subItemNbr2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="errorReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="errorReasonDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="origAttribValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="remarks" maxOccurs="unbounded" minOccurs="0">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                   &lt;element name="remarks_LNG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "code", "codeDescription", "type",
				"itemNbr", "subItemNbr", "subItemNbr2", "errorReason",
				"errorReasonDescription", "origAttribValue", "remarks" })
		public static class ResponseDetail {

			/** The code. */
			@XmlElement(required = true)
			protected String code;

			/** The code description. */
			protected String codeDescription;

			/** The type. */
			protected String type;

			/** The item nbr. */
			protected String itemNbr;

			/** The sub item nbr. */
			protected String subItemNbr;

			/** The sub item nbr 2. */
			protected String subItemNbr2;

			/** The error reason. */
			protected String errorReason;

			/** The error reason description. */
			protected String errorReasonDescription;

			/** The orig attrib value. */
			protected String origAttribValue;

			/** The remarks. */
			protected List<ResponseMessage.CustResponse.ResponseDetail.Remarks> remarks;

			/**
			 * Gets the value of the code property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCode() {
				return code;
			}

			/**
			 * Sets the value of the code property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCode(String value) {
				this.code = value;
			}

			/**
			 * Gets the value of the codeDescription property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCodeDescription() {
				return codeDescription;
			}

			/**
			 * Sets the value of the codeDescription property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCodeDescription(String value) {
				this.codeDescription = value;
			}

			/**
			 * Gets the value of the type property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getType() {
				return type;
			}

			/**
			 * Sets the value of the type property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setType(String value) {
				this.type = value;
			}

			/**
			 * Gets the value of the itemNbr property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getItemNbr() {
				return itemNbr;
			}

			/**
			 * Sets the value of the itemNbr property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setItemNbr(String value) {
				this.itemNbr = value;
			}

			/**
			 * Gets the value of the subItemNbr property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSubItemNbr() {
				return subItemNbr;
			}

			/**
			 * Sets the value of the subItemNbr property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSubItemNbr(String value) {
				this.subItemNbr = value;
			}

			/**
			 * Gets the value of the subItemNbr2 property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSubItemNbr2() {
				return subItemNbr2;
			}

			/**
			 * Sets the value of the subItemNbr2 property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSubItemNbr2(String value) {
				this.subItemNbr2 = value;
			}

			/**
			 * Gets the value of the errorReason property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getErrorReason() {
				return errorReason;
			}

			/**
			 * Sets the value of the errorReason property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setErrorReason(String value) {
				this.errorReason = value;
			}

			/**
			 * Gets the value of the errorReasonDescription property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getErrorReasonDescription() {
				return errorReasonDescription;
			}

			/**
			 * Sets the value of the errorReasonDescription property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setErrorReasonDescription(String value) {
				this.errorReasonDescription = value;
			}

			/**
			 * Gets the value of the origAttribValue property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getOrigAttribValue() {
				return origAttribValue;
			}

			/**
			 * Sets the value of the origAttribValue property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setOrigAttribValue(String value) {
				this.origAttribValue = value;
			}

			/**
			 * Gets the value of the remarks property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the remarks property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getRemarks().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link ResponseMessage.CustResponse.ResponseDetail.Remarks }
			 * 
			 * @return the remarks
			 */
			public List<ResponseMessage.CustResponse.ResponseDetail.Remarks> getRemarks() {
				if (remarks == null) {
					remarks = new ArrayList<ResponseMessage.CustResponse.ResponseDetail.Remarks>();
				}
				return this.remarks;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *         &lt;element name="remarks_LNG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "remarks", "remarksLNG" })
			public static class Remarks {

				/** The remarks. */
				@XmlElement(required = true)
				protected String remarks;

				/** The remarks LNG. */
				@XmlElement(name = "remarks_LNG")
				protected String remarksLNG;

				/**
				 * Gets the value of the remarks property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getRemarks() {
					return remarks;
				}

				/**
				 * Sets the value of the remarks property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setRemarks(String value) {
					this.remarks = value;
				}

				/**
				 * Gets the value of the remarksLNG property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getRemarksLNG() {
					return remarksLNG;
				}

				/**
				 * Sets the value of the remarksLNG property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setRemarksLNG(String value) {
					this.remarksLNG = value;
				}

				@Override
				public String toString() {
					return "Remarks [remarks=" + remarks + ", remarksLNG=" + remarksLNG + "]";
				}

				
				
			}

			@Override
			public String toString() {
				return "ResponseDetail [code=" + code + ", codeDescription=" + codeDescription + ", type=" + type
						+ ", itemNbr=" + itemNbr + ", subItemNbr=" + subItemNbr + ", subItemNbr2=" + subItemNbr2
						+ ", errorReason=" + errorReason + ", errorReasonDescription=" + errorReasonDescription
						+ ", origAttribValue=" + origAttribValue + ", remarks=" + remarks + "]";
			}
			
			

		}

		@Override
		public String toString() {
			return "CustResponse [tpDocNbr=" + tpDocNbr + ", customRefNbr=" + customRefNbr + ", dispCode=" + dispCode
					+ ", sendingCntry=" + sendingCntry + ", itemNbr=" + itemNbr + ", responseDetail=" + responseDetail
					+ ", remarks=" + remarks + "]";
		}
		
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="responseSenderReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="responseReceiverReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="senderInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="lodgementStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="lodgementStatusDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="dates" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="dateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="dateTimeKind" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "responseSenderReference",
			"responseReceiverReference", "senderInfo", "lodgementStatus",
			"lodgementStatusDescription", "dates" })
	public static class LodgementStatusResponse {

		/** The response sender reference. */
		protected String responseSenderReference;

		/** The response receiver reference. */
		protected String responseReceiverReference;

		/** The sender info. */
		protected String senderInfo;

		/** The lodgement status. */
		protected String lodgementStatus;

		/** The lodgement status description. */
		protected String lodgementStatusDescription;

		/** The dates. */
		protected List<ResponseMessage.LodgementStatusResponse.Dates> dates;

		/**
		 * Gets the value of the responseSenderReference property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getResponseSenderReference() {
			return responseSenderReference;
		}

		/**
		 * Sets the value of the responseSenderReference property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setResponseSenderReference(String value) {
			this.responseSenderReference = value;
		}

		/**
		 * Gets the value of the responseReceiverReference property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getResponseReceiverReference() {
			return responseReceiverReference;
		}

		/**
		 * Sets the value of the responseReceiverReference property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setResponseReceiverReference(String value) {
			this.responseReceiverReference = value;
		}

		/**
		 * Gets the value of the senderInfo property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSenderInfo() {
			return senderInfo;
		}

		/**
		 * Sets the value of the senderInfo property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSenderInfo(String value) {
			this.senderInfo = value;
		}

		/**
		 * Gets the value of the lodgementStatus property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getLodgementStatus() {
			return lodgementStatus;
		}

		/**
		 * Sets the value of the lodgementStatus property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setLodgementStatus(String value) {
			this.lodgementStatus = value;
		}

		/**
		 * Gets the value of the lodgementStatusDescription property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getLodgementStatusDescription() {
			return lodgementStatusDescription;
		}

		/**
		 * Sets the value of the lodgementStatusDescription property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setLodgementStatusDescription(String value) {
			this.lodgementStatusDescription = value;
		}

		/**
		 * Gets the value of the dates property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the dates property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getDates().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link ResponseMessage.LodgementStatusResponse.Dates }
		 * 
		 * @return the dates
		 */
		public List<ResponseMessage.LodgementStatusResponse.Dates> getDates() {
			if (dates == null) {
				dates = new ArrayList<ResponseMessage.LodgementStatusResponse.Dates>();
			}
			return this.dates;
		}

		
		@Override
		public String toString() {
			return "LodgementStatusResponse [responseSenderReference=" + responseSenderReference
					+ ", responseReceiverReference=" + responseReceiverReference + ", senderInfo=" + senderInfo
					+ ", lodgementStatus=" + lodgementStatus + ", lodgementStatusDescription="
					+ lodgementStatusDescription + ", dates=" + dates + "]";
		}



		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="dateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="dateTimeKind" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "dateTime", "dateTimeKind" })
		public static class Dates {

			/** The date time. */
			protected String dateTime;

			/** The date time kind. */
			protected String dateTimeKind;

			/**
			 * Gets the value of the dateTime property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDateTime() {
				return dateTime;
			}

			/**
			 * Sets the value of the dateTime property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setDateTime(String value) {
				this.dateTime = value;
			}

			/**
			 * Gets the value of the dateTimeKind property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDateTimeKind() {
				return dateTimeKind;
			}

			/**
			 * Sets the value of the dateTimeKind property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setDateTimeKind(String value) {
				this.dateTimeKind = value;
			}

			@Override
			public String toString() {
				return "Dates [dateTime=" + dateTime + ", dateTimeKind=" + dateTimeKind + "]";
			}
			
		}

	}

	@Override
	public String toString() {
		return "ResponseMessage [sourceID=" + sourceID + ", evwRef=" + evwRef + ", iChgCtrl=" + iChgCtrl
				+ ", vesselCode=" + vesselCode + ", loadPort=" + loadPort + ", exportVoyage=" + exportVoyage
				+ ", dischargePort=" + dischargePort + ", dischargeVoyage=" + dischargeVoyage + ", sentTS=" + sentTS
				+ ", recdTS=" + recdTS + ", lodgementStatusResponse=" + lodgementStatusResponse + ", custResponse="
				+ custResponse + "]";
	}
	
}
